### ISSUE TITLE
Question about inf norm results

### ISSUE THREAD

**Issue by msqiqi10** [alevine0/smoothingGenGaussian#1]
Hi:

Thanks for your hard work on random smoothing!
I'm trying to run a baseline when p=inf, and there's also a result of such a setting in your result presented in your paper.
However, if setting p=inf, the randgn_like function gives nan value. 
Could you please help me with this?

Thanks!

**Comment by alevine0** [comment]
Hi,
 As  mentioned in the readme, this repository calculates the two bounds on the certificates for the p-norm with q-shaped generalized gaussian in the case where p = q. This corresponds to figures 5, 6, and 7 in the paper. The p= inf case shown in figures 8 and 9 is with standard Gaussian noise (q=2). As described in the paper, this is computed using  Equation 1; which (for fixed dimension d) is a constant scaling factor from Cohen certificate for the the p=q=2 case. So for these figures, we just took the p=q=2 result, and applied the appropriate scaling.

Hope this helps!
